rottenpotatoes/config/routes.rb
Rottenpotatoes::Application.routes.draw do
resources :movies

  match 'movies/similar_movies/:id/' => 'movies#similar_movies', :as => :similar_movies

end

rottenpotatoes/app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :title, :rating, :description, :release_date, :director
  @@all_ratings = ['G','PG','PG-13','R']
  def self.all_ratings
     @@all_ratings
  end
 
end

rottenpotatoes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

rottenpotatoes/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
   attr_accessor :checked_rating

  def show
    id = params[:id] # retrieve movie ID from URI route
    @movie = Movie.find(id) # look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  end

  def index
    #reset_session
    @all_ratings = Movie.all_ratings
    @sort = params[:sort]
    if ((params[:sort] == nil && session[:sort] != nil) || (params[:ratings] == nil && session[:ratings] != nil))
        redirect_to movies_path(:sort => params[:sort] || session[:sort], :ratings => params[:ratings] || session[:ratings])
    end
    if (params[:ratings] != nil)
        @checked_rating = params[:ratings]
        session[:ratings] = params[:ratings]
    else 
        @checked_rating = {"G"=>"1", "PG"=>"1", "PG-13" => "1","R" => "1"} 
    end
    if (@sort == "title" || @sort == "release_date")
        session[:sort] = params[:sort]
	      @movies = Movie.where("rating IN (?)", @checked_rating.keys).order(params[:sort])
    else
        @movies = Movie.where("rating IN (?)", @checked_rating.keys)
    end
  end

  def new
    # default: render 'new' template
    reset_session
  end

  def create
    @movie = Movie.create!(params[:movie])
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    @movie.update_attributes!(params[:movie])
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' deleted."
    redirect_to movies_path
  end

  def similar_movies
    id = params[:id] # retrieve movie ID from URI route
    director = params[:director]
    @movie = Movie.find(id) # look up movie by unique ID
    @similar_movies = Movie.find_all_by_director(@movie.director)
    if (@movie.director == "") || (@movie.director.nil?)
      flash[:notice] = "'#{@movie.title}' has no director info"
      redirect_to '/movies'
    end
  end

end

rottenpotatoes/app/helpers/application_helper.rb
module ApplicationHelper
end

rottenpotatoes/app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Rotten Potatoes!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %h1.title Rotten Potatoes!
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      = yield

rottenpotatoes/app/views/movies/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Movie

= form_tag movie_path(@movie), :method => :put do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = label :movie, :director, 'Director'
  = text_field :movie, 'director'

  = submit_tag 'Update Movie Info'

rottenpotatoes/app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 All Movies
= form_tag movies_path, :method => :get, :id => "ratings_form" do 
  Include: 
  - @all_ratings.each do |rating|
    = rating
    = check_box_tag "ratings[#{rating}]", 1, @checked_rating.include?(rating)
  = submit_tag 'Refresh', :id => "ratings_submit"

%table#movies
  %thead
    %tr
      -if @sort == "title"
        %th.hilite Movie Title
      -else 
        %th= link_to "Movie Title", movies_path(:sort => 'title'), :id => "title_header"
      %th Rating
      -if @sort == "release_date"
        %th.hilite Release Date
      -else
        %th= link_to "Release Date", movies_path(:sort => 'release_date'), :id => "release_date_header"
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Add new movie', new_movie_path

rottenpotatoes/app/views/movies/new.html.haml
%h1 Create New Movie

= form_tag movies_path do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = label :movie, :director, 'Director'
  = text_field :movie, 'director'

  = submit_tag 'Save Changes'

rottenpotatoes/app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Director:
    = @movie.director
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

%h3 Description:

%p#description= @movie.description

= link_to 'Edit', edit_movie_path(@movie)
= button_to 'Delete', movie_path(@movie), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Find Movies With Same Director', similar_movies_path(@movie)
%br
= link_to 'Back to movie list', movies_path

rottenpotatoes/app/views/movies/similar_movies.html.haml
-# in app/views/movies/show.html.haml

%h2 Other movies directed by: #{@movie.director}

%table#movies
  %thead
    %tr
      -if @sort == "title"
        %th.hilite Movie Title
      -else 
        %th= link_to "Movie Title", movies_path(:sort => 'title'), :id => "title_header"
      %th Rating
      -if @sort == "release_date"
        %th.hilite Release Date
      -else
        %th= link_to "Release Date", movies_path(:sort => 'release_date'), :id => "release_date_header"
      %th More Info
  %tbody
    - @similar_movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= movie.director
        %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Back to movie list', movies_path